---
- name: Install vim on servers
  hosts: servers
  remote_user: root
  tasks:

  - name: Install vim  
    ansible.builtin.apt:
      name: vim
      state: present
  - name: Install zip
    ansible.builtin.apt:
      name: zip
      state: present
    when: ansible_distribution == "CentOS"
  - name: Touch the same file, but add/remove some permissions
    ansible.builtin.file:
      path: /tmp/this_is_centos
      state: touch
      mode: u+rw,g-wx,o-rwx


