---
- name: Install vim on servers
  hosts: servers
  remote_user: root
  tasks:

  - name: Install vim  
    ansible.builtin.apt:
      name: vim
      state: present
  - name: Install zip
    ansible.builtin.apt:
      name: zip
      state: present
        
        #  - name: Include taskapp.yml
        #  ansible.builtin.include_tasks:
        #  file: taskapp.yml
